namespace MackySoft.AgentSkills.Agents.Hosts;

/// <summary> Represents the files generated by one agent host adapter. </summary>
internal sealed class AgentHostArtifactSet
{
    /// <summary> Initializes a host artifact set. </summary>
    public AgentHostArtifactSet (IReadOnlyList<AgentHostArtifactFile> files)
    {
        ArgumentNullException.ThrowIfNull(files);
        if (files.Count == 0 || files.Any(static file => file is null))
        {
            throw new ArgumentException("Agent host artifacts must contain at least one file.", nameof(files));
        }

        Files = Array.AsReadOnly(files.ToArray());
    }

    /// <summary> Gets the adapter-relative artifact files. </summary>
    public IReadOnlyList<AgentHostArtifactFile> Files { get; }
}
