using MackySoft.AgentSkills.Shared;

namespace MackySoft.AgentSkills.Hosts.Contracts;

/// <summary> Represents the files generated by one agent host adapter. </summary>
internal sealed class AgentHostArtifactSet
{
    /// <summary> Initializes a host artifact set. </summary>
    public AgentHostArtifactSet (IReadOnlyList<AgentHostArtifactFile> files)
    {
        ArgumentNullException.ThrowIfNull(files);
        if (files.Count == 0
            || files.Any(static file => file is null)
            || files.GroupBy(static file => file.RelativePath, PackageRelativePath.PortableFileSystemComparer).Any(static group => group.Count() != 1))
        {
            throw new ArgumentException("Agent host artifacts must contain at least one file and use portable unique paths.", nameof(files));
        }

        Files = Array.AsReadOnly(files.ToArray());
    }

    /// <summary> Gets the adapter-relative artifact files. </summary>
    public IReadOnlyList<AgentHostArtifactFile> Files { get; }
}
